name: deploy-prod

on:
  push:
    tags:        
      - prod-v*
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: macos-latest

    steps:
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      - name: Deploy to build servers
        run: |
          echo "Deploying build4.gonative.io"
          
          cat > deploy.sh << 'END'
            #!/bin/bash
            set -e
            
            cd ~/prod/build2
            git checkout -- .
            git fetch
            echo "Checking out ${{ steps.extract_tag.outputs.tag }}"
            git checkout ${{ steps.extract_tag.outputs.tag }}
            npm install

            echo "Stopping builder"
            forever stopall

            echo "Starting builder"
            ./prod-forever.sh 2
            
            echo "Deployed prod"
          END

          scp -o StrictHostKeyChecking=no deploy.sh builder@build4.gonative.io:deploy.sh
          ssh -o StrictHostKeyChecking=no builder@build4.gonative.io bash --login ./deploy.sh
