name: iOS Build and Archive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Archive the app
      run: |
        # Clean the build and archive
        xcodebuild -workspace MachiMart.xcworkspace \
                   -scheme MachiMart \
                   -sdk iphoneos \
                   -configuration Release \
                   -archivePath build/MachiMart.xcarchive \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                   clean archive

    - name: Export .ipa
      run: |
        # Export the IPA from the archived build
        xcodebuild -exportArchive \
                   -archivePath build/MachiMart.xcarchive \
                   -exportPath build/ipa \
                   -exportOptionsPlist ExportOptions.plist
